### ISSUE TITLE
failed to parse Referer header: hostname deploy.cloud.run not supported

### ISSUE THREAD

**Issue by anishkny** [GoogleCloudPlatform/cloud-run-microservice-template-nodejs#115]
On clicking "Run on Google Cloud" button in README which points to: https://deploy.cloud.run/

**Comment by averikitsch** [comment]
Hi @anishkny thank you for the issue report. When you click on the button it should reroute you to Cloud Shell in the Google Cloud console. Unfortunately the link doesn't work outside the button in the README without additional url parameters.
